from __future__ import annotations

import textwrap
from neuralflow.execution.workflow_analyzer import AnalyzedWorkflow, NodeSpec


class CodeExporter:
    def __init__(self, workflow: AnalyzedWorkflow) -> None:
        self.workflow = workflow

    # ── helpers ──────────────────────────────────────────────────────────────

    def _agent_nodes(self) -> list[NodeSpec]:
        return [n for n in self.workflow.nodes if n.type == "agent"]

    def _node_by_id(self, nid: str) -> NodeSpec | None:
        for n in self.workflow.nodes:
            if n.id == nid:
                return n
        return None

    # ── CrewAI export ─────────────────────────────────────────────────────────

    def export_crewai(self) -> str:
        wf = self.workflow
        agent_nodes = self._agent_nodes()

        agent_blocks: list[str] = []
        task_blocks: list[str] = []
        agent_var_names: list[str] = []

        for i, node in enumerate(agent_nodes):
            d = node.data
            var = f"agent_{i}"
            agent_var_names.append(var)
            role = d.get("role") or node.name
            goal = d.get("systemPrompt") or d.get("goal") or "Complete the assigned task."
            backstory = d.get("backstory") or ""
            model = d.get("model") or "gpt-4o"

            agent_blocks.append(
                f'{var} = Agent(\n'
                f'    role={role!r},\n'
                f'    goal={goal!r},\n'
                f'    backstory={backstory!r},\n'
                f'    llm={model!r},\n'
                f'    allow_delegation={str(d.get("allowDelegation", False))},\n'
                f'    verbose=True,\n'
                f')'
            )

            task_desc = d.get("task") or d.get("description") or "Complete assigned task."
            task_blocks.append(
                f'task_{i} = Task(\n'
                f'    description={task_desc!r},\n'
                f'    expected_output="Task result",\n'
                f'    agent={var},\n'
                f')'
            )

        process = "Process.hierarchical" if wf.has_manager else "Process.sequential"
        agents_list = "[" + ", ".join(agent_var_names) + "]"
        tasks_list = "[" + ", ".join(f"task_{i}" for i in range(len(agent_nodes))) + "]"

        script = textwrap.dedent(f"""\
            # Auto-generated by NeuralFlow — CrewAI export
            # Requires: pip install crewai

            from crewai import Agent, Task, Crew, Process


            # ── Agents ──────────────────────────────────────────────────────────────────

            {chr(10).join(chr(10).join(b.splitlines()) for b in agent_blocks)}

            # ── Tasks ───────────────────────────────────────────────────────────────────

            {chr(10).join(chr(10).join(b.splitlines()) for b in task_blocks)}

            # ── Crew ────────────────────────────────────────────────────────────────────

            crew = Crew(
                agents={agents_list},
                tasks={tasks_list},
                process={process},
                verbose=True,
            )


            if __name__ == "__main__":
                result = crew.kickoff(inputs={{}})
                print(result)
            """)
        return script

    # ── LangGraph export ──────────────────────────────────────────────────────

    def export_langgraph(self) -> str:
        wf = self.workflow
        agent_nodes = self._agent_nodes()
        router_nodes = [n for n in wf.nodes if n.type == "router"]

        node_fn_blocks: list[str] = []
        add_node_lines: list[str] = []
        add_edge_lines: list[str] = []

        def safe_var(nid: str) -> str:
            return "node_" + nid.replace("-", "_")

        for node in agent_nodes:
            var = safe_var(node.id)
            model = node.data.get("model") or "gpt-4o"
            system_prompt = node.data.get("systemPrompt") or node.name

            node_fn_blocks.append(
                f'def {var}(state: dict) -> dict:\n'
                f'    messages = state.get("messages", [])\n'
                f'    response = litellm.completion(\n'
                f'        model={model!r},\n'
                f'        messages=[{{"role": "system", "content": {system_prompt!r}}}] + messages,\n'
                f'    )\n'
                f'    reply = response.choices[0].message.content\n'
                f'    return {{"messages": messages + [{{"role": "assistant", "content": reply}}]}}\n'
            )
            add_node_lines.append(f'graph.add_node("{node.id}", {var})')

        for node in router_nodes:
            var = safe_var(node.id)
            outgoing = [e for e in wf.edges if e.source == node.id]
            conditions: list[str] = []
            for e in outgoing:
                conditions.append(
                    f'    if state.get("route") == {e.condition!r}:\n'
                    f'        return {e.target!r}'
                )
            fallback = outgoing[0].target if outgoing else "__end__"
            node_fn_blocks.append(
                f'def {var}(state: dict) -> dict:\n'
                f'    return state\n'
                f'\n'
                f'def {var}_router(state: dict) -> str:\n'
                + ("\n".join(conditions) + "\n" if conditions else "")
                + f'    return {fallback!r}\n'
            )
            add_node_lines.append(f'graph.add_node("{node.id}", {var})')

        for edge in wf.edges:
            src_node = self._node_by_id(edge.source)
            if src_node and src_node.type == "router":
                router_var = safe_var(edge.source)
                add_edge_lines.append(
                    f'graph.add_conditional_edges("{edge.source}", {router_var}_router)'
                )
            else:
                add_edge_lines.append(
                    f'graph.add_edge("{edge.source}", "{edge.target}")'
                )

        # Entry edge from START to first topo node
        if wf.topo_order:
            add_edge_lines.insert(0, f'graph.add_edge("__start__", "{wf.topo_order[0]}")')

        script = textwrap.dedent("""\
            # Auto-generated by NeuralFlow — LangGraph export
            # Requires: pip install langgraph litellm

            import litellm
            from langgraph.graph import StateGraph, MessagesState, END


            # ── Node functions ───────────────────────────────────────────────────────────

            """)

        script += "\n\n".join(node_fn_blocks)
        script += "\n\n"
        script += "# ── Graph assembly ──────────────────────────────────────────────────────────\n\n"
        script += "graph = StateGraph(dict)\n\n"
        script += "\n".join(add_node_lines) + "\n\n"
        # deduplicate conditional edges
        seen_cond: set[str] = set()
        unique_edge_lines: list[str] = []
        for line in add_edge_lines:
            if "conditional_edges" in line:
                if line in seen_cond:
                    continue
                seen_cond.add(line)
            unique_edge_lines.append(line)
        script += "\n".join(unique_edge_lines) + "\n\n"
        script += textwrap.dedent("""\
            app = graph.compile()


            if __name__ == "__main__":
                result = app.invoke({"messages": [{"role": "user", "content": "Start workflow"}]})
                print(result)
            """)
        return script
